### ISSUE TITLE
Default elasticsearch_network_host overrides other settings

### ISSUE THREAD

**Issue by jgoodall** [Stouts/Stouts.elasticsearch#6]
If I set the following, settings they are basically ignored because the role sets the `elasticsearch_network_host` to be `127.0.0.1` by default. I would like to disable that default setting and customize using the bind and publish (rather than setting them to the same).

```
elasticsearch_network_bind_host:
elasticsearch_network_publish_host:
```

**Comment by klen** [comment]
Thank you for the feedback. I've made a fix for that.
